question_data = [
        {"type": "boolean",
         "difficulty": "easy", "category": "Science: Computers",
         "question": "The Windows ME operating system was released in the year 2000.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "The Windows 7 operating system has six main editions.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "The logo for Snapchat is a Bell.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "The first IBM PC was released in 1981.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "Time on Computers is measured via the EPOX System.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "Ada Lovelace is often considered the first computer programmer.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
         "question": "&quot;HTML&quot; stands for Hypertext Markup Language.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean",
         "difficulty": "easy",
         "category": "Science: Computers",
         "question": "JavaScript derives from a later version of Java",
         "correct_answer": "False",
         "incorrect_answers": ["True"]}
]
