name: Day 32 - Birthday Wisher

on:
  schedule:
    # Runs at 05:00 UTC daily (07:00 CEST Berlin time)
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Recreate private birthdays.csv from secret
        run: |
          echo "${{ secrets.BIRTHDAYS_CSV_DATA }}" > Day-32/birthday-wisher/birthdays.csv
          
      - name: Run script
        env:
            MY_EMAIL: ${{ secrets.MY_EMAIL }}
            MY_EMAIL_PASSWORD: ${{ secrets.MY_EMAIL_PASSWORD }}
        run: |
          cd Day-32/birthday-wisher
          python main.py
